version: "2"
services:

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
    mem_limit: 768m
    mem_reservation: 128M
    cpus: 0.25

  # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    mem_limit: 1G
    mem_reservation: 128M
    cpus: 0.5      

  # Collector
  otel-collector:
    image: ${OTELCOL_IMG}
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./data/:/home/data/
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317"        # OTLP gRPC receiver
      - "55670:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one
    mem_limit: 768m
    mem_reservation: 128M
    cpus: 0.25


  demo-client:
    build:
      dockerfile: Dockerfile
      context: ./client
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - DEMO_SERVER_ENDPOINT=http://demo-server:7080/hello
    depends_on:
      - demo-server
    mem_limit: 768m
    mem_reservation: 128M
    cpus: 0.25

  demo-server:
    build:
      dockerfile: Dockerfile
      context: ./server
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
    ports:
      - "7080:7080"
    depends_on:
      - otel-collector
    mem_limit: 768m
    mem_reservation: 128M
    cpus: 0.25

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    mem_limit: 768m
    mem_reservation: 128M
    cpus: 0.25

  # Agent
  otel-agent:
    image: ${OTELCOL_IMG}
    command: ["--config=/etc/otel-agent-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-agent-config.yaml:/etc/otel-agent-config.yaml
      - ./data/:/home/data/
    depends_on:
      - otel-collector
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.25


  zipkin-emitter:
    image: omnition/synthetic-load-generator:1.0.25
    environment:
      - ZIPKINV2_JSON_URL=http://otel-agent:9411/api/v2/spans
    depends_on:
      - otel-agent
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.25


  metrics-load-generator:
    build:
      dockerfile: Dockerfile
      context: ./app
    environment:
      - OTEL_AGENT_ENDPOINT=otel-agent:4317
    depends_on:
      - otel-agent
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.25

  # Synthetic load generators
  jaeger-emitter:
    image: omnition/synthetic-load-generator:1.0.25
    environment:
      - JAEGER_COLLECTOR_URL=http://otel-agent:14268
    depends_on:
      - otel-agent
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.25

